### ISSUE TITLE
Heat shield mass

### ISSUE THREAD

**Issue by futrtrubl** [NathanKell/DeadlyReentry#22]
The base mass of the 2.5m heatshield is 0.06t which agrees roughly with the mass of the Huygens 2.7m heatshield at 79kg (though that included ablative mass).
However, the smaller 1.25m heatshield despite being smaller weighs 3x as much at 0.2t. Actually all the other heatshields have the same base structural mass of 0.2t

**Comment by NathanKell** [comment]
I think you meant to post this here: https://github.com/Starwaster/DeadlyReentry/
I haven't been maintainer of Deadly Reentry in a long, long time. :)

**Comment by futrtrubl** [comment]
Indeed I did ;']

Regards.
