### ISSUE TITLE
Kerbals explode on eva

### ISSUE THREAD

**Issue by DennisKerman** [NathanKell/DeadlyReentry#24]
Hi,
Unfortunately my Kerbals tend to randomly explode while on eva. If new Kerbal (eg from contract) is joining and going eva for the transfer he/she WILL explode for sure. 
Other Kerbals somtimes burn... like if there was athmosphere and they were parts close to failing.
Using KAS/KIS and manipulating stuff there is a ranfom chance my Kerbals will go *poof*...

**Comment by NathanKell** [comment]
Wrong repo. Try https://github.com/Starwaster/DeadlyReentry/

**Comment by DennisKerman** [comment]
thanks. sry! Great mod tho. I love it. thanks alot!!!
